name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libsdl2-dev \
            libssl-dev \
            python3-dev \
            python3-pip \
            python3-setuptools \
            zlib1g-dev
          python3 -m pip install --upgrade pip wheel
          python3 -m pip install cython==0.29.21  # Install specific version of Cython
          python3 -m pip install buildozer
          
      - name: Download Android SDK tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip -d android-sdk
          export ANDROID_HOME=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          
      - name: Install Aidl
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
        
      - name: Build APK
        run: buildozer android debug
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ./bin/*.apk
